type: http
name: List application documents
url: '{{baseUrl}}/applications/:applicationId/documents'
method: GET
headers:
  - key: Accept
    value: application/json
pathVariables:
  - key: applicationId
    value: string
examples:
  - response:
      statusCode: 200
      statusText: OK
      body:
        type: json
        content: |-
          [
            {
              "id": "string",
              "applicationId": "string",
              "documentType": "string",
              "fileName": "string",
              "uploadedAt": "1997-04-22T06:15:29.134Z",
              "verificationStatus": "pending"
            },
            {
              "id": "string",
              "applicationId": "string",
              "documentType": "string",
              "fileName": "string",
              "uploadedAt": "1955-03-27T18:11:17.345Z",
              "verificationStatus": "pending"
            }
          ]
      headers:
        - key: Content-Type
          value: application/json
    name: List of documents
