type: http
name: Get application details
url: '{{baseUrl}}/applications/:applicationId'
method: GET
headers:
  - key: Accept
    value: application/json
pathVariables:
  - key: applicationId
    value: string
examples:
  - response:
      statusCode: 200
      statusText: OK
      body:
        type: json
        content: |-
          {
            "id": "string",
            "applicantId": "string",
            "productType": "string",
            "requestedAmount": 7948.577872371796,
            "termMonths": 4734,
            "status": "denied",
            "createdAt": "2018-01-14T02:52:57.805Z",
            "updatedAt": "2021-10-23T04:59:45.732Z",
            "underwritingResult": {
              "applicationId": "string",
              "status": "pending",
              "decision": "referred_to_manual",
              "riskScore": 92,
              "evaluatedAt": "1952-03-16T15:04:29.648Z"
            }
          }
      headers:
        - key: Content-Type
          value: application/json
    name: Application details
  - response:
      statusCode: 404
      statusText: Not Found
      body:
        type: json
        content: |-
          {
            "code": "string",
            "message": "string",
            "details": {}
          }
      headers:
        - key: Content-Type
          value: application/json
    name: Application not found
